openapi: 3.0.3
info:
  title: Site Service API
  version: 1.0.0
  description: >
    API for managing energy sites.
    
    NOTE: Write operations (POST, PUT, PATCH, DELETE) are asynchronous (Fire-and-Forget).
    They return HTTP 202 Accepted immediately after queuing the event.
    The data is eventually consistent.

servers:
  - url: /api/v1

tags:
  - name: Site
    description: Operations related to Site management

paths:
  /sites:
    post:
      summary: Create a new site (Async)
      operationId: createSite
      tags:
        - Site
      description: >
        Queues a creation event for a new site. 
        Returns immediately with the generated ID and status 'ACCEPTED'.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteRequest'
      responses:
        '202':
          description: Creation request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: './common-error.yaml#/components/schemas/ApiError'

    get:
      summary: Get a list of sites
      operationId: listSites
      tags:
        - Site
      description: Retrieves a paginated list of sites (Synchronous read from Cache/DB).
      parameters:
        - name: user_id
          in: query
          description: Filter sites by User ID
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          description: Page number (0-indexed)
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          description: Number of items per page
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        '200':
          description: List of sites retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSitesResponse'

  /sites/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the site
        schema:
          type: string
          format: uuid

    get:
      summary: Get a site by ID
      operationId: getSite
      tags:
        - Site
      responses:
        '200':
          description: Site found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteResponse'
        '404':
          description: Site not found
          content:
            application/json:
              schema:
                $ref: './common-error.yaml#/components/schemas/ApiError'

    put:
      summary: Update a site (Async Full Update)
      operationId: updateSite
      tags:
         - Site
      description: >
        Queues an update event. 
        The worker will merge the new data with the existing state.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteRequest'
      responses:
        '202':
          description: Update request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'
        '400':
          description: Invalid input

    patch:
      summary: Patch a site (Async Partial Update)
      operationId: patchSite
      tags:
        - Site
      description: >
        Queues a partial update event. 
        Only the fields present in the payload will be updated by the worker.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteRequest'
      responses:
        '202':
          description: Patch request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'

    delete:
      summary: Delete a site (Async)
      operationId: deleteSite
      tags:
        - Site
      description: Queues a deletion event.
      responses:
        '202':
          description: Deletion request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncOperationResponse'

components:
  schemas:
    # --- Shared Objects ---
    GeoLocation:
      type: object
      description: Geographical coordinates
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double

    # --- Responses ---

    # NEW: Response object for Async Operations (202 Accepted)
    AsyncOperationResponse:
      type: object
      description: Minimal response indicating the operation was queued.
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the resource being created, updated, or deleted.
        status:
          type: string
          enum: [ACCEPTED, PENDING]
          example: ACCEPTED
        message:
          type: string
          description: Optional info message
          example: "Request queued for processing"

    SiteResponse:
      type: object
      description: The full Site entity representation (Used only in GET)
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        location:
          $ref: '#/components/schemas/GeoLocation'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ListSitesResponse:
      type: object
      description: Wrapper object containing the list of sites and pagination metadata
      properties:
        sites:
          type: array
          items:
            $ref: '#/components/schemas/SiteResponse'
        total_count:
          type: integer
          format: int32
        total_pages:
          type: integer
          format: int32

    # --- Requests ---
    SiteRequest:
      type: object
      required:
        - user_id
        - name
      properties:
        user_id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        location:
          $ref: '#/components/schemas/GeoLocation'